### ISSUE TITLE
NoSuchMethodError in LGBMDataset.createFromMat on Win (Java)

### ISSUE THREAD

**Issue by jornd13** [metarank/metarank#1182]
I'm trying to run the Java lightgbm4j wrapper on Windows and I cannot get around the following error, no matter which library versions etc. I use. The call is embedded in proprietary code (see below). I rely on the Maven version of LGBM4J:

<dependency>
    <groupId>io.github.metarank</groupId>
    <artifactId>lightgbm4j</artifactId>
    <version>3.3.2-5</version>
</dependency>

Switching to the float variant of the method does not help either.

When I try different (lower) lib versions from Maven I end up with UnsatisfiedLinkError (see at the bottom).

Stack trace for use of lightgbm4j 3.3.2-5:

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/H:/m2/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/H:/m2/org/slf4j/slf4j-log4j12/1.7.26/slf4j-log4j12-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "Thread-7" java.lang.NoSuchMethodError: com.microsoft.ml.lightgbm.lightgbmlib.new_doubleArray(J)Lcom/microsoft/ml/lightgbm/SWIGTYPE_p_double;
	at io.github.metarank.lightgbm4j.LGBMDataset.createFromMat(LGBMDataset.java:93)
	at weka.classifiers.functions.LGBMClassifier.buildClassifier(LGBMClassifier.java:78)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:2049)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:1679)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.generateClassifierGeneric(WekaClassifierAdapter.java:2317)
	at control.MFNController.trainWekaClassifier(MFNController.java:5392)
	at control.MFNController.generatePQReportWekaClassifier(MFNController.java:4562)
	at control.ParameterSpaceExplorationAgent.run(ParameterSpaceExplorationAgent.java:1847)

______________________________________________________
Stack trace for use of lower versions of lightgbm4j:

Exception in thread "Thread-7" java.lang.UnsatisfiedLinkError: com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp()J
	at com.microsoft.ml.lightgbm.lightgbmlibJNI.new_voidpp(Native Method)
	at com.microsoft.ml.lightgbm.lightgbmlib.new_voidpp(lightgbmlib.java:489)
	at io.github.metarank.lightgbm4j.LGBMDataset.createFromMat(LGBMDataset.java:51)
	at weka.classifiers.functions.LGBMClassifier.buildClassifier(LGBMClassifier.java:78)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:2049)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.createClonesSubRoutine(WekaClassifierAdapter.java:1679)
	at knowledgeConnector.externalMLMethods.WekaClassifierAdapter.generateClassifierGeneric(WekaClassifierAdapter.java:2317)
	at control.MFNController.trainWekaClassifier(MFNController.java:5392)

**Comment by shuttie** [comment]
There's definitly an issue with a 3-d party library here, but apart from mmlspark I can't spot anything suspicious from the get go. I suggest you double-confirming that the mmlspark dependency is not still somehow transitively pulled into the classpath - as it's the only one bundling the native library, causing the dll hell.

How do you build your project? Is it a maven-based pom.xml? Can you show the build file - or at least the dependencies section of it.

We might consider adding a special check in the lightgbm4j code loading the native libs to perform a check if mmlspark is in classpath and native libs differ from the expected ones. But it won't fix your issue, just explicitly states that still the mmlspark somehow leaked into the classpath.
