### ISSUE TITLE
: and / cannot be used in search queries using Redis persistence layer

### ISSUE THREAD

**Issue by herrfennessey** [metarank/metarank#1279]
Due to how the redis keys are structured and serialized/deserialized using `/` as a split character, and `:` as a delimiter between the search term and the item ID, neither can be used when passing queries into metarank

`s/ctr_impression/irf=query:my query:589` - works
`s/ctr_impression/irf=query:A/V cables:589` - doesn't work and throws 500's 

https://github.com/metarank/metarank/blob/master/src/main/scala/ai/metarank/fstore/codec/StoreFormat.scala#L54

This also breaks the `import` function once it encounters a search term with any of these reserved characters

(original query was `5 1/4 speakers`)
```
2024-03-27 06:57:01 java.lang.Exception: cannot parse key List(ctr_impression, irf=query:5 1, 4 speakers:012562243184)
2024-03-27 06:57:01     at ai.metarank.fstore.codec.StoreFormat$$anon$1.decodeNoPrefix(StoreFormat.scala:56)
2024-03-27 06:57:01     at ai.metarank.fstore.file.FilePeriodicCounterFeature$.decode(FilePeriodicCounterFeature.scala:83)
````

```
2024-03-27 07:24:44 java.lang.IllegalArgumentException: cannot parse item field scope value 'query:call of duty: modern warfare 3:047875333734'
2024-03-27 07:24:44     at ai.metarank.model.Scope$.fromString(Scope.scala:91)
2024-03-27 07:24:44     at ai.metarank.fstore.codec.StoreFormat$$anon$1.decodeNoPrefix(StoreFormat.scala:55)
```

**Comment by shuttie** [comment]
@herrfennessey I'll make a bugfix release today, so please test. If things still are breaking, feel free to reopen the issue.

**Comment by david-fennessey** [comment]
Sure can, thank you!

**Comment by shuttie** [comment]
https://github.com/metarank/metarank/releases/tag/0.7.8

**Comment by herrfennessey** [comment]
Works great, thank you @shuttie! Tested on load, train, and serve
