### ISSUE TITLE
ERR Protocol error: invalid bulk length

### ISSUE THREAD

**Issue by shuttie** [metarank/metarank#318]
When we rank too many items over too many features, the redis read request becomes too large:
```
20:20:22.701 ERROR org.http4s.server.service-errors - Error servicing request: POST /rank from 127.0.0.1
redis.clients.jedis.exceptions.JedisDataException: ERR Protocol error: invalid bulk length
        at redis.clients.jedis.Protocol.processError(Protocol.java:96)
        at redis.clients.jedis.Protocol.process(Protocol.java:137)
        at redis.clients.jedis.Protocol.read(Protocol.java:192)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
        at redis.clients.jedis.Connection.getOne(Connection.java:298)
        at redis.clients.jedis.Connection.executeCommand(Connection.java:123)
        at redis.clients.jedis.Jedis.mget(Jedis.java:818)
        at io.findify.featury.connector.redis.RedisStore.$anonfun$read$3(RedisStore.scala:47)
        at apply @ io.findify.featury.connector.redis.RedisStore.$anonfun$read$2(RedisStore.scala:47)
        at flatMap @ io.findify.featury.connector.redis.RedisStore.$anonfun$read$2(RedisStore.scala:47)
        at make @ ai.metarank.mode.inference.FlinkMinicluster$.resource(FlinkMinicluster.scala:13)
        at make @ ai.metarank.mode.inference.FlinkMinicluster$.resource(FlinkMinicluster.scala:13)
        at use @ ai.metarank.mode.inference.Inference$.$anonfun$run$4(Inference.scala:33)
        at flatMap @ ai.metarank.mode.inference.api.RankApi.$anonfun$rerank$2(RankApi.scala:34)
        at apply @ ai.metarank.mode.inference.api.RankApi.rerank(RankApi.scala:33)
        at flatMap @ ai.metarank.mode.inference.api.RankApi.rerank(RankApi.scala:33)
        at flatMap @ ai.metarank.mode.inference.api.RankApi$$anonfun$1.$anonfun$applyOrElse$1(RankApi.scala:25)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
```

So we should split such requests into smaller chunks and send them in parallel instead.

**Comment by shuttie** [comment]
Actually that's the main reason why demo was constantly failing on show-hn

**Comment by shuttie** [comment]
Fixed in https://github.com/metarank/metarank/pull/333
