### ISSUE TITLE
Getting java.lang.reflect.InaccessibleObjectException when following tutorial

### ISSUE THREAD

**Issue by pow202** [metarank/metarank#340]
Following the Data Bootstrapping step of the [tutorial](https://github.com/metarank/metarank/blob/master/doc/tutorial_ranklens.md#1-data-bootstraping) gives an error.

Steps taken:
1. create test directory containing the following files:
    1. `config.yml` - as per the one found in the repo.
    2. `events.jsonl.gz` - as per the one found in the repo.
    5. `metarank-0.2.5.jar` - from the releases page of the repo.
2. Open windows powershell in that directory, and run: `java -cp .\metarank-0.2.5.jar ai.metarank.mode.bootstrap.Bootstrap --events .\ --out .\ --config .\config.yml`

I get the following error:
```21:52:53.628 INFO  a.metarank.mode.bootstrap.Bootstrap$ - starting historical data processing
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final int java.lang.Class.ANNOTATION accessible: module java.base does not "opens java.lang" to unnamed module @11bd0f3b
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:106)
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:132)
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:132)
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:132)
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:69)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:2139)
        at org.apache.flink.streaming.api.datastream.DataStream.clean(DataStream.java:203)
        at org.apache.flink.streaming.api.datastream.KeyedStream.<init>(KeyedStream.java:160)
        at org.apache.flink.streaming.api.datastream.KeyedStream.<init>(KeyedStream.java:130)
        at org.apache.flink.streaming.api.scala.DataStream.keyBy(DataStream.scala:441)
        at org.apache.flink.streaming.api.scala.extensions.impl.acceptPartialFunctions.OnDataStream.keyingBy(OnDataStream.scala:76)
        at ai.metarank.mode.bootstrap.Bootstrap$.groupFeedback(Bootstrap.scala:130)
        at ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$15(Bootstrap.scala:72)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.run(Bootstrap.scala:63)
        at map @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$13(Bootstrap.scala:58)
        at apply @ ai.metarank.config.Config$.$anonfun$load$7(Config.scala:34)
        at map @ ai.metarank.config.Config$.$anonfun$load$7(Config.scala:34)
        at flatMap @ ai.metarank.config.Config$.$anonfun$load$6(Config.scala:33)
        at flatMap @ ai.metarank.config.Config$.load(Config.scala:32)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$12(Bootstrap.scala:57)
        at apply @ ai.metarank.mode.FileLoader$.loadLocal(FileLoader.scala:41)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$11(Bootstrap.scala:56)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$9(Bootstrap.scala:55)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$9(Bootstrap.scala:55)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$7(Bootstrap.scala:54)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$7(Bootstrap.scala:54)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$5(Bootstrap.scala:53)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$5(Bootstrap.scala:53)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$3(Bootstrap.scala:52)
```

Java version is:
```
PS>java --version
java 18 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
```

I've tried using the `--add-opens` flag like so:
`java --add-opens java.base/java.lang=ALL-UNNAMED -cp .\metarank-0.2.5.jar ai.metarank.mode.bootstrap.Bootstrap --events .\ --out .\ --config .\config.yml` 
but instead get another error:
`java.lang.IllegalArgumentException: Can not get final java.lang.Class field java.lang.Class.componentType on java.lang.Class`

**Comment by shuttie** [comment]
I guess it's happening due to Apache Flink 1.14 (which we use right now) not supporting Java >= 11. AFAIK the 1.15 release will bring a ton of compatibility fixes, but it is planned to happen somewhere in April 2022.

Before that I suggest to try to use a Java11. I guess we should update docs about it.

**Comment by pow202** [comment]
Ah my bad. I kept coming across things when searching for solutions implying that Flink might not be playing nice with Java >= 11 but the tutorial specifically said JVM 11+ and I was trying to avoid making an Oracle account so I assumed it would be ok.

Using Java11 gets me past that error but I now get another error:
```
org.apache.flink.util.FlinkRuntimeException: Could not create committable serializer.
        at org.apache.flink.connector.file.sink.FileSink.getCommittableSerializer(FileSink.java:152)
        at org.apache.flink.streaming.runtime.translators.SinkTransformationTranslator.internalTranslate(SinkTransformationTranslator.java:110)
        at org.apache.flink.streaming.runtime.translators.SinkTransformationTranslator.translateForBatch(SinkTransformationTranslator.java:64)
        at org.apache.flink.streaming.runtime.translators.SinkTransformationTranslator.translateForBatch(SinkTransformationTranslator.java:48)
        at org.apache.flink.streaming.api.graph.StreamGraphGenerator.translate(StreamGraphGenerator.java:820)
        at org.apache.flink.streaming.api.graph.StreamGraphGenerator.transform(StreamGraphGenerator.java:551)
        at org.apache.flink.streaming.api.graph.StreamGraphGenerator.generate(StreamGraphGenerator.java:315)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getStreamGraph(StreamExecutionEnvironment.java:2083)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getStreamGraph(StreamExecutionEnvironment.java:2069)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1915)
        at org.apache.flink.streaming.api.scala.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.scala:839)
        at ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$15(Bootstrap.scala:81)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.run(Bootstrap.scala:63)
        at map @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$13(Bootstrap.scala:58)
        at apply @ ai.metarank.config.Config$.$anonfun$load$7(Config.scala:34)
        at map @ ai.metarank.config.Config$.$anonfun$load$7(Config.scala:34)
        at flatMap @ ai.metarank.config.Config$.$anonfun$load$6(Config.scala:33)
        at flatMap @ ai.metarank.config.Config$.load(Config.scala:32)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$12(Bootstrap.scala:57)
        at apply @ ai.metarank.mode.FileLoader$.loadLocal(FileLoader.scala:41)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$11(Bootstrap.scala:56)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$9(Bootstrap.scala:55)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$9(Bootstrap.scala:55)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$7(Bootstrap.scala:54)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$7(Bootstrap.scala:54)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$5(Bootstrap.scala:53)
        at flatMap @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$5(Bootstrap.scala:53)
        at apply @ ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$3(Bootstrap.scala:52)
Caused by: java.io.IOException: Found local file path with authority 'C:\metarank_tutorial\out' in path 'file://C:%5Cmetarank_tutorial%5Cout/state'. Hint: Did you forget a slash? (correct path would be 'file:///C:\metarank_tutorial\out/state')
        at org.apache.flink.core.fs.FileSystem.getUnguardedFileSystem(FileSystem.java:477)
        at org.apache.flink.core.fs.FileSystem.get(FileSystem.java:409)
        at org.apache.flink.connector.file.sink.FileSink$BulkFormatBuilder.createBucketWriter(FileSink.java:474)
        at org.apache.flink.connector.file.sink.FileSink$BulkFormatBuilder.getCommittableSerializer(FileSink.java:465)
        at org.apache.flink.connector.file.sink.FileSink.getCommittableSerializer(FileSink.java:147)
        at org.apache.flink.streaming.runtime.translators.SinkTransformationTranslator.internalTranslate(SinkTransformationTranslator.java:110)
        at org.apache.flink.streaming.runtime.translators.SinkTransformationTranslator.translateForBatch(SinkTransformationTranslator.java:64)
        at org.apache.flink.streaming.runtime.translators.SinkTransformationTranslator.translateForBatch(SinkTransformationTranslator.java:48)
        at org.apache.flink.streaming.api.graph.StreamGraphGenerator.translate(StreamGraphGenerator.java:820)
        at org.apache.flink.streaming.api.graph.StreamGraphGenerator.transform(StreamGraphGenerator.java:551)
        at org.apache.flink.streaming.api.graph.StreamGraphGenerator.generate(StreamGraphGenerator.java:315)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getStreamGraph(StreamExecutionEnvironment.java:2083)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getStreamGraph(StreamExecutionEnvironment.java:2069)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1915)
        at org.apache.flink.streaming.api.scala.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.scala:839)
        at ai.metarank.mode.bootstrap.Bootstrap$.$anonfun$run$15(Bootstrap.scala:81)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:358)
        at cats.effect.IOFiber.execR(IOFiber.scala:1327)
        at cats.effect.IOFiber.run(IOFiber.scala:139)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:523)
```
Should I close this issue and open another specifically for this new error?

**Comment by shuttie** [comment]
Oh, Microsoft Windows! We struggled a bit with setting up our CI to run a complete test suite on Win, but looks like that it's time to do another attempt.
