### ISSUE TITLE
file-based cts may fail on wrong path

### ISSUE THREAD

**Issue by shuttie** [metarank/metarank#859]
when config has the following definition:
```
train:
  type: file
  path: /tmp/nonexistent.dat
  format: binary
```
then:
```
java.io.FileNotFoundException: training-data.bin/cts (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at ai.metarank.fstore.clickthrough.FileClickthroughStore$.$anonfun$create$3(FileClickthroughStore.scala:58)
	at apply @ ai.metarank.fstore.clickthrough.FileClickthroughStore$.$anonfun$create$2(FileClickthroughStore.scala:58)
	at main$ @ ai.metarank.main.Main$.main(Main.scala:29)
	at main$ @ ai.metarank.main.Main$.main(Main.scala:29)
	at main$ @ ai.metarank.main.Main$.main(Main.scala:29)
	at apply @ ai.metarank.fstore.clickthrough.FileClickthroughStore$.create(FileClickthroughStore.scala:57)
	at use @ ai.metarank.util.analytics.AnalyticsReporter$.ping(AnalyticsReporter.scala:27)
	at apply @ ai.metarank.fstore.redis.RedisPersistence$.$anonfun$create$4(RedisPersistence.scala:169)
	at fromCompletableFuture @ ai.metarank.fstore.redis.RedisPersistence$.$anonfun$create$4(RedisPersistence.scala:169)
	at void @ ai.metarank.util.analytics.AnalyticsReporter$.ping(AnalyticsReporter.scala:45)
	at void @ ai.metarank.util.analytics.AnalyticsReporter$.ping(AnalyticsReporter.scala:45)
	at use @ ai.metarank.util.analytics.AnalyticsReporter$.ping(AnalyticsReporter.scala:27)
```

**Comment by shuttie** [comment]
fixed in 0.6.1
